### ISSUE TITLE
Several WIT samples assume existence of certain work items

### ISSUE THREAD

**Issue by vtbassmatt** [Microsoft/vsts-dotnet-samples#101]
Several of the WIT sample methods assume certain work items exist in the target account. This causes 12 separate exceptions during execution of the "wit" area.

If the samples need work items with certain properties to exist, they should arrange for those items to exist.

CommentsSample.GetSingleWorkItemComment (assumes "23")
RecycleBinSample.GetDeletedWorkItem (assumes there's a page of results)
RecycleBinSample.GetMultipledDeletedWorkItems (72, 73, 81)
RecycleBinSample.RestoreWorkItem (page)
RecycleBinSample.RestoreMultipleWorkItems (72, 73, 81)
RecycleBinSample.PermenentlyDeleteMultipleWorkItems (72, 73, 81)
WorkItemsSample.GetWorkItemsWithSpecificFields (assumes a key that's missing)
WorkItemsSample.GetWorkItemsWithLinksAndAttachments (50)
WorkItemsSample.MoveToAnotherProject (page)
WorkItemsSample.UpdateLinkComment (assumes a revision number)
WorkItemsSample.UpdateWorkItemAddHyperLink (id = -1?)
WorkItemsSample.UpdateWorkItemAddCommitLink (assumes revision number)

**Comment by danhellem** [comment]
resolved
