### ISSUE TITLE
CreateChangeset. Maximum request size exceeded.

### ISSUE THREAD

**Issue by Feroks** [Microsoft/vsts-dotnet-samples#104]
When i try to check-in several files via API i am getting a following error:
"The maximum request size of **26214400** bytes was exceeded"

I am using a Microsoft.TeamFoundationServer.Client library to make the requests. Here is the URL of the requests taken from Fiddler:
"/tfs/DefaultCollection/_apis/tfvc/changesets"

I guess this limit is specified in some web.config of TFS, but i could not find it. How can i increase the limit?

**Comment by vtbassmatt** [comment]
Hi, thanks for stopping by. This is just a repository of samples using the VSTS API, not the place for support or bugs in VSTS/TFS themselves.

Bug reports for TFS/VSTS go [here](http://developercommunity.visualstudio.com/). This sounds like it may be a support request, which goes [here](https://www.visualstudio.com/team-services/support/).
