### ISSUE TITLE
WorkItemTrackingHttpClient.CreateAttachmentAsync(...).Result hangs

### ISSUE THREAD

**Issue by bruceburge** [Microsoft/vsts-dotnet-samples#106]
when attempting to use the code from the samples specifically [this](https://github.com/Microsoft/vsts-dotnet-samples/blob/c1caebb2c87c5fc09254a2c58f0a6a7d49b2d719/ClientLibrary/Snippets/Microsoft.TeamServices.Samples.Client/WorkItemTracking/AttachmentsSample.cs#L35)
`AttachmentReference attachment = workItemTrackingClient.CreateAttachmentAsync(@filePath).Result;`

The task never finishes, I can verify through fiddler that the request is goes out, and the response back is send similar to
`{"id":"2253e426-3d97-4834-9206-d35ea0a2373f","url":"https://xxxxxxx.visualstudio.com/DefaultCollection/_apis/wit/attachments/2253e426-3d97-4834-9206-d35ea0a2373f?fileName=C:%5Ctemp%5CModels%5CArtifact.cs"}`

This response and the URL it provides are valid and contain the correct file.

**Comment by bruceburge** [comment]
been over a month, no response... 👎

**Comment by danhellem** [comment]
Bruce, sorry for the delays. I just loaded up the project and not having any issues. Are you looking at the samples [here ](https://github.com/Microsoft/vsts-dotnet-samples/blob/master/ClientLibrary/Snippets/Microsoft.TeamServices.Samples.Client/WorkItemTracking/WorkItemsSample.cs#L547)?

What is the size of your file?

Have you tried a direct http endpoint call. [here is the docs](https://docs.microsoft.com/en-us/rest/api/vsts/wit/attachments/create).

**Comment by bruceburge** [comment]
```C#
            // upload attachment to store and get a reference to that file
            AttachmentReference attachmentReference = workItemTrackingClient.CreateAttachmentAsync(filePath).Result;
```

this is the line present in both the sample I linked, and the sample you linked, both have the same effect of not returning.

Calling directly through Http does work, and is currently the work around being deployed.

What environment are you testing under, 
I'm using vs 2017, windows 10 x64, .net 4.7 

Nuget Info 
![image](https://user-images.githubusercontent.com/6773890/37411142-196fa23a-2770-11e8-9908-6f2dd9158b36.png)

**Comment by bruceburge** [comment]
I'm not sure if it will make a difference, but today the issue on [developercommunity ](https://developercommunity.visualstudio.com/content/problem/194421/workitemtrackingclientcreateattachmentasyncfilepat.html) forum was changed to "Under Consideration" for what that is worth.

Have you had a chance to review this?

**Comment by danhellem** [comment]
Sorry for the delay Bruce. I don't work on this repo full time so I don't monitor it as much as I should. I just re-ran the client sample for [add attachment](https://github.com/Microsoft/vsts-dotnet-samples/blob/master/ClientLibrary/Snippets/Microsoft.TeamServices.Samples.Client/WorkItemTracking/WorkItemsSample.cs#L522) and it is working as expected. If you keep having troubles let me know. I can bring this up with the engineers and have them double check for us.

**Comment by cschaef** [comment]
Hi Bruce, try this:

``

**Comment by ChunLi0819** [comment]
> Hi Bruce, try this:
> 
> ```
> AttachmentReference attachment = null;
> using (FileStream stream = new FileStream(file.FullName, FileMode.Open))
>     attachment = workItemTrackingClient.CreateAttachmentAsync(stream, file.Name).Result;
> ```

Don't know why but this way did work. Thanks.
