### ISSUE TITLE
Getting test results using VSTS rest API

### ISSUE THREAD

**Issue by kksevta** [Microsoft/vsts-dotnet-samples#11]
I am using Nodejs for consuming rest API of VSTS
Getting Builds and work items is working fine.

But I am confused about the endpoint which will return me the test results of particular build.
Kindly help me with this.

**Comment by sdavis3** [comment]
@kksevta Check out https://www.visualstudio.com/en-us/docs/integrate/extensions/reference/client/api/tfs/testmanagement/restclient/testhttpclient2_2
