### ISSUE TITLE
Validate work item

### ISSUE THREAD

**Issue by ArminGeisbusch** [Microsoft/vsts-dotnet-samples#120]
Hello,

how does the validate option works with CreateWorkItemAsync().
Can someone provide a sample please?

Thanks, Armin

**Comment by danhellem** [comment]
We added a quick sample [here](https://github.com/Microsoft/vsts-dotnet-samples/blob/master/ClientLibrary/Snippets/Microsoft.TeamServices.Samples.Client/WorkItemTracking/WorkItemsSample.cs#L363)

validateOnly is used when you want to check and make sure the create or update will work without actually saving the data. It just runs the wi through all the rules to make sure it is legit.
