### ISSUE TITLE
Need a sample to get list of all work items worked on between two builds

### ISSUE THREAD

**Issue by rsaa** [Microsoft/vsts-dotnet-samples#123]
We need a way to create release notes automatically. All our work is managed using work items in VSTS and worked against code inside git repository in VSTS. So all information is there. We need to a way to list all work items worked on between two build numbers.

**Comment by danhellem** [comment]
[This should help](https://docs.microsoft.com/en-us/rest/api/vsts/build/builds/get%20work%20items%20between%20builds?view=vsts) you in getting what you need. We don't have .net client library sample yet though.
