### ISSUE TITLE
Removing Attachments

### ISSUE THREAD

**Issue by sremiger1** [Microsoft/vsts-dotnet-samples#125]
In the example removing attachments you declare rev to 0

What is rev?

I am attempting to use the samples but my rev 8 appears to be related to revisions(history), not attachments.

**Comment by danhellem** [comment]
You will need to get the revision value . then use that value + 1 in your work item update call to remove the attachment.

https://docs.microsoft.com/en-us/rest/api/vsts/wit/work%20items/update?view=vsts#remove_an_attachment
