### ISSUE TITLE
Authenticating with OAUTH Token

### ISSUE THREAD

**Issue by nickmza** [Microsoft/vsts-dotnet-samples#126]
Hi, 

Is there an example of how to authenticate with an OAUTH Access or Refresh token?

Currently I am using my Refresh token to retrieve an Access Token (based on the code from the VSTS Auth Samples). I then use the Access Token to create a VssOAuthAcccessToken and pass this into the connection. 

All my calls result in an HTTP 302 'Found' response. I have checked the outbound request and the Authorise header is not set so I assume I am not setting up the connection correctly but I cannot see what I am doing wrong.

Regards

Nick

**Comment by justmarks** [comment]
Yes, we have another GitHub repo for authentication samples.  Here's the Oauth one: https://github.com/Microsoft/vsts-auth-samples/tree/master/OAuthWebSample

**Comment by nickmza** [comment]
Hi,

I've seen this, thanks. My question is if there is a sample that shows how
to use the Refresh Token created in the OAuthWebSample with the Client API?
I've tried passing using the token to create a VssCredential but this does
not seem to work.

Regards

Nick

**Comment by justmarks** [comment]
The refresh token is simply used to refresh your access token, it's not used directly to access the Client API.  

To use the OAuth AccessToken with the client libraries, make these calls:

VssOAuthAccessTokenCredential oAuthCredential = new VssOAuthAccessTokenCredential(oAuthResult.AccessToken);
VssConnection connection = new VssConnection(new Uri(String.Format("https://{0}.visualstudio.com", vstsAccountName)), oAuthCredential);

Put this in a try/catch block and if the expiration exception is returned, use the refresh token to get a new access token

**Comment by nickmza** [comment]
Hi,

This is great! Thanks for your help.

Regards

Nick
