### ISSUE TITLE
Sample for grabbing latest commits from a specified branch/ref?

### ISSUE THREAD

**Issue by csteez** [Microsoft/vsts-dotnet-samples#130]
Could we get a sample around grabbing latest commits? 
Specifically I'm curious how to get the latest version of a file from a specified branch using the GitHTTPClient. 

Even a small non-official sample would be greatly appreciated.

The use case I'm trying to solve is when the file we care about is known, and we have a known branch, but we want that branch's version, which may or may not be the same as master.

**Comment by vtbassmatt** [comment]
`GitItem item = gitClient.GetItemAsync(repo.Id, filename, includeContent: true).Result;` should do it. Where:
* repo.Id is a GUID identifying the repository
* filename is the path from the repo root to the file (e.g. "/readmd.md")

I'm working on adding this to the samples.

**Comment by vtbassmatt** [comment]
The sample doesn't show how to pick another branch (it uses the default). You can pass a `GitVersionDescriptor` with the type set to "branch" and the appropriate name into `GetItemAsync`.

**Comment by vtbassmatt** [comment]
Oh! Sorry, I misunderstood your question. You actually want the [/refs endpoint](https://docs.microsoft.com/en-us/rest/api/vsts/git/refs/get?view=vsts-rest-5.0) for that -- although I notice we have a bug on that doc page which I will get addressed.

There's already a sample for the plural version of that endpoint, [here](https://github.com/Microsoft/vsts-dotnet-samples/blob/master/ClientLibrary/Snippets/Microsoft.TeamServices.Samples.Client/Git/RefsSample.cs#L24). When you have a `GitRef` object that you know is a branch, you can ask for its `.ObjectId` to get the commit ID.
