### ISSUE TITLE
Any timelime/plan for .net core support?

### ISSUE THREAD

**Issue by MoimHossain** [Microsoft/vsts-dotnet-samples#137]
Hi there, thanks for such nice REST client, helps a lot in automation works.

I have seen an issue related to .net core, but there is nothing mentioned about the plan (if there are any) or road map if this SDK will have a .net core version released. Would you please let us know, if there is any plan/ETA there?

**Comment by Grandizer** [comment]
Any word on when a actual .Net Core version will be release?

**Comment by danhellem** [comment]
This is a duplicate of issue #93
