### ISSUE TITLE
To get the Label of the layout

### ISSUE THREAD

**Issue by shivarajalagond** [Microsoft/vsts-dotnet-samples#138]
Hi, 
Is there a way to get the label of the layout from VSTS?
For example, 
For the Details layout I have number of fields,
workitem.Fields  will give all the fields.

But is there a way to find out which layout each field belongs to ?

Thanks in advance.

**Comment by danhellem** [comment]
You can get the list of fields per work item type. Try [this API](https://docs.microsoft.com/en-us/rest/api/vsts/processes/fields/get%20work%20item%20type%20fields?view=vsts-rest-4.1)
