### ISSUE TITLE
integrate.visualstudio.com does not exist

### ISSUE THREAD

**Issue by ranjan-ranjan** [Microsoft/vsts-dotnet-samples#171]
When we go to https://github.com/Microsoft/vsts-dotnet-samples, there is https://integrate.visualstudio.com/ on the page which does not exist. Can we delete it and given another helpful link

**Comment by danhellem** [comment]
Yeah we made some changes to the url's here. I will get this fixed

**Comment by danhellem** [comment]
Fixed
