### ISSUE TITLE
Sign-in to on-premise tfs

### ISSUE THREAD

**Issue by baloghpeter2** [Microsoft/vsts-dotnet-samples#180]
Hello Team!

It might be me who is missing something but I was searching for a way to sign in to an on-promise TFS server through C# console app. Is there a way to do that like VssCredentials or something similar?

Thank you for your answer!

**Comment by MarcAndreViau** [comment]
Try to do it with a VssClientCredential like this

`var clientCredential = new VssClientCredentials(new WindowsCredential(false), new VssFederatedCredential(true), CredentialPromptType.PromptIfNeeded, TaskScheduler.Default);`

You can then get your projects for example: 

`var connection = new VssConnection(url, clientCredential ).GetClient<ProjectHttpClient>();
 var projects = connection .GetProjects().Result;`

A typical url should resemble this format: "http://foo.bar.com/tfs/SomethingElse"

Hope this helps!

**Comment by baloghpeter2** [comment]
It worked! Thank you for your help!
