### ISSUE TITLE
How to clone a work item

### ISSUE THREAD

**Issue by tomaustin700** [Microsoft/vsts-dotnet-samples#219]
Hi,

Are you able to provide me with an example showing how to clone a work item? The WorkItem class from Microsoft.TeamFoundation.WorkItemTracking.Client has a .Clone method however I am using Microsoft.TeamFoundation.WorkItemTracking.WebApi as I am now using .Net core and the WorkItem class has no .Clone.

What is the best way to do this? Thanks.

**Comment by danhellem** [comment]
Unfortunately we have not exposed a REST endpoint for "clone". It is not a common ask. To get this to work on your own you would need to get a work item and then look through the fields and create a new patch document. then use that to save a new work item.

Also, if this is a priority for you please go and [create a suggestion ticket](https://developercommunity.visualstudio.com/spaces/21/index.html) and get some votes. If it becomes a priority we will invest.

Finally, if you do decide to attack this on your own. Please share a code example and we will add it into this repo for others to enjoy :)
