### ISSUE TITLE
Create Bug Sample missing in project and the sample not work

### ISSUE THREAD

**Issue by SummerSun** [Microsoft/vsts-dotnet-samples#26]
I find the create bug sample by searching directly in the git repo, but nothing when I clone it to local. Turns out the [file](https://github.com/Microsoft/vsts-dotnet-samples/blob/ba1cb905cd4ad2d9d800d59909ee65cec438dd70/Microsoft.TeamServices.Samples.Client/WorkItemTracking/Sample.cs) is not include in project **Microsoft.TeamServices.Samples.Client**.

Besides, the sample does not work. I captured the request, performed it in fiddler. Got bad request response claiming that: Rule Error for field Issue Type. Though the error message is clear, there is nothing related in the code sample.

Finally, I got it work by adding the object in request body:
```js
{
    "op": "add",
    "path": "/fields/Microsoft.DevDiv.IssueType",
    "value": "Code Defect"
}
```

Hope it could get fixed. Thank you.

**Comment by danhellem** [comment]
This is because you a specific rule on your work item type that requires an issue type value. That is not a normal required field.
