### ISSUE TITLE
QueriesSample.DeleteQueryOrFolderByPath() should delete a previously created sample query

### ISSUE THREAD

**Issue by willsmythe** [Microsoft/vsts-dotnet-samples#29]
This sample method is currently deleting a hard-coded query `My Queries/Sample`, but should instead be deleting a sample query created earlier.

One idea is to reorder the methods you already have ...

1. Create a sample query (store ID in $sampleQueryId) 
2. Delete the sample query by ID (using $sampleQueryId)
3. Undelete this query
4. Delete the same query again by path (likely means setting a $sampleQueryPath context variable in step 1)

**Comment by danhellem** [comment]
Completed
