### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by szbence-dgital** [Microsoft/vsts-dotnet-samples#39]
I'd be interested how to list all the ACLs on objects (projects, git repos, release configurations etc)

**Comment by vtbassmatt** [comment]
I'll see if I can find some time to do this one soon. (Other contributors, feel free to steal it from me if you get to it before I do.)

**Comment by vtbassmatt** [comment]
Work in progress: https://github.com/vtbassmatt/vsts-dotnet-samples/tree/list-acls

**Comment by vtbassmatt** [comment]
Addressed with #47.

**Comment by szbence-dgital** [comment]
Thanks!
