### ISSUE TITLE
When will the Release APIs be supported in the .NET client library

### ISSUE THREAD

**Issue by MisinformedDNA** [Microsoft/vsts-dotnet-samples#40]
It appears they are in preview, but having those preview APIs in the .NET client library would be helpful. Any timeline for this?

Specifically, I'm looking for two things that will be set off from a 3rd party service:
1. Start a Release deployment
2. Approve/deny a Release deployment

**Comment by MisinformedDNA** [comment]
I tried to create a Release using the REST API, but I keep getting 404s. See [gist](https://gist.github.com/MisinformedDNA/5c7a0eaa1675917d09b68220583ec77c).

**Comment by vtbassmatt** [comment]
I believe the Release APIs are in the client library now (there are [samples for them](https://github.com/Microsoft/vsts-dotnet-samples/blob/master/ClientLibrary/Snippets/Microsoft.TeamServices.Samples.Client/Release/ReleasesSample.cs)).
