### ISSUE TITLE
How to get Builds information using C#

### ISSUE THREAD

**Issue by naniNaidunani** [Microsoft/vsts-dotnet-samples#44]
Need to get Builds info using C#

**Comment by naniNaidunani** [comment]
Need to get Builds info using C#

**Comment by naniNaidunani** [comment]
Need to get Builds info using C#

**Comment by danhellem** [comment]
Try https://docs.microsoft.com/en-us/rest/api/vsts/build/?view=vsts
and https://github.com/Microsoft/vsts-dotnet-samples/blob/master/ClientLibrary/Snippets/Microsoft.TeamServices.Samples.Client/Build/BuildsSample.cs
