### ISSUE TITLE
Not Found exception

### ISSUE THREAD

**Issue by Allann** [Microsoft/vsts-dotnet-samples#49]
I receive a 'Not Found' exception at this point.  

https://github.com/Microsoft/vsts-dotnet-samples/blob/d4958e2eff2f61c1719465dd8045b7474217f012/ClientLibrary/Snippets/Microsoft.TeamServices.Samples.Client/WorkItemTracking/Sample.cs#L370

I'm thinking it's because I end up with 389 ids being passed to the query.  I assume this is way too many since a query returning a smaller result set works fine.  My issue is that I have no idea what the upper limit is and whether the query is truely 'Not Found' or whether it's a data issue.

**Comment by sferg-msft** [comment]
Sorry you’re hitting this issue.  Unfortunately you’ve hit a limitation of the URL length.  Once the URL length has been exceeded, the server just gets the truncated version, so odds are high that the truncated work item id is not valid.

I recommend limiting your calls to 200 ids at a time.

**Comment by vfrank66** [comment]
Do you have an example of batching?
