### ISSUE TITLE
How can i get attachment id from WorkItemRelation?

### ISSUE THREAD

**Issue by apsbrar** [Microsoft/vsts-dotnet-samples#55]
I want to download an attachment on a workitem and I can see that there is a sample for download attachment,  but I don't know how to get the attachment GUID from the workitem

`
var workItem = witClient.GetWorkItemAsync(Convert.ToInt32(id), expand: WorkItemExpand.Relations).Result;`
`

                        foreach (var relation in workItem.Relations)
                        {
                            if (relation.Rel == "Hyperlink")
                            {
                                // dont know how to get GUID for attachment
                            }
                        }`

**Comment by sferg-msft** [comment]
A Hyperlink isn’t an attachment, just a link to an external website.

You want to look for the one that says it’s an AttachedFile and the URL will be the one to download the attachment.

**Comment by apsbrar** [comment]
Thanks, I was barking up the wrong tree :-(
Of course Hyperlink is not an attachment, I had to use System.Net.WebClient to download items from hyperlink
