### ISSUE TITLE
JsonSerializationException on converting value when using in WebApi project

### ISSUE THREAD

**Issue by MarkS21** [Microsoft/vsts-dotnet-samples#57]
I get a 

> Newtonsoft.Json.JsonSerializationException: Error converting value \"Microsoft.IdentityModel.Claims.ClaimsIdentity;**{identity}**\" to type 'Microsoft.VisualStudio.Services.Identity.IdentityDescriptor'. Path 'authenticatedUser.descriptor', line 1, position 188. ---> System.ArgumentException: Could not cast or convert from System.String to Microsoft.VisualStudio.Services.Identity.IdentityDescriptor.

when i'm trying to create a work item in my web api project.

`var hostUri = new Uri("TfsAccountUrl");`
`var connection = new VssConnection(hostUri, new VssBasicCredential(string.Empty, "PAT"));`    
`var workItemClient = await connection.GetClientAsync<WorkItemTrackingHttpClient>();`

When i'm using the exact same code in a console application it works fine. I can only guess that this has something to do with my JsonSerializer Settings which are currently so in the web api project:

`var jSettings = new JsonSerializerSettings();`
`var jsonFormatter = httpConfiguration.Formatters.JsonFormatter;`
`jsonFormatter.SerializerSettings.ContractResolver = new CamelCasePropertyNamesContractResolver();`
`jSettings.Formatting = Formatting.Indented;`
`jSettings.ContractResolver = new CamelCasePropertyNamesContractResolver();`                      
`jsonFormatter.Indent = configHelper.Configuration.JsonSerializer.Indent;`                       
`jsonFormatter.SerializerSettings.DateTimeZoneHandling = DateTimeZoneHandling.Utc`
`JsonConvert.DefaultSettings = () => jSettings;`

**Comment by jmezach** [comment]
Just ran into the same issue in an Azure Function app. Any updates on this? Looks like the serializer settings are shared somehow.

**Comment by diegomodolo** [comment]
I am having the same issue, I've already upgraded the Azure Functions SDK but the problem continues.
And as @MarkS21, if I run a console application with the same code in prior to my main project everything works.

**Comment by saprunitin** [comment]
Same issue while using the TeamFoundationClient nuget in Azure functions. 
_Newtonsoft.Json.JsonSerializationException: 'Error converting value 
ArgumentException: Could not cast or convert from System.String to Microsoft.VisualStudio.Services.Identity.IdentityDescriptor.

Any update on this ?

**Comment by PaulMilla** [comment]
@cloudmaker-inc  I used the workaround someone someone described in #212  and had that work for me

```
TypeDescriptor.AddAttributes(typeof(IdentityDescriptor), new TypeConverterAttribute(typeof(IdentityDescriptorConverter).FullName));

TypeDescriptor.AddAttributes(typeof(SubjectDescriptor), new TypeConverterAttribute(typeof(SubjectDescriptorConverter).FullName));
```
