### ISSUE TITLE
Attachment uploaded using API is unauthorized to read for other users

### ISSUE THREAD

**Issue by CodingNawab** [Microsoft/vsts-dotnet-samples#58]
Repro steps:
1) Use the API and the code here to upload an attachment and get the attachemntReference.Url and try to get to the url using another user in the team project. 
2) The file should be available but it throws the following back;
     Note: (I have tried PAT & DefaultCredentials in my file uplaod)
`{"$id":"1","innerException":null,"message":"VS402330: Unauthorized Read access to the attachment under the areas ","typeName":"Microsoft.TeamFoundation.WorkItemTracking.Server.WorkItemUnauthorizedAttachmentException, Microsoft.TeamFoundation.WorkItemTracking.Server","typeKey":"WorkItemUnauthorizedAttachmentException","errorCode":0,"eventId":3200} `

3) Also tried the same using the REST calls and still the same behavior.
Note: The other users I am using are created in the Azure AD on the default domain - ie - user.account@xyz.onmicrosoft.com

**Comment by danhellem** [comment]
Have you checked to ensure your area path security is correct for the identity trying to access the attachment?

If you are still having trouble please let me know and we can dig into it further.

**Comment by spirosvp** [comment]
Why is this issue closed? Do have a solution? I am currently having the same issue.
