### ISSUE TITLE
When creating an area with child nodes, the child nodes are not created

### ISSUE THREAD

**Issue by smithrobs** [Microsoft/vsts-dotnet-samples#59]
I followed the [example for CreateArea](https://github.com/Microsoft/vsts-dotnet-samples/blob/master/ClientLibrary/Snippets/Microsoft.TeamServices.Samples.Client/WorkItemTracking/ClassificationNodesSample.cs#L80) and ran it against my VSTS instance. It creates the parent node, but none of the children.

`POST https://MYACCOUNT.visualstudio.com/{guid}/_apis/wit/classificationNodes/Areas​`

```json
{"id":0,"identifier":"00000000-0000-0000-0000-000000000000","name":"Third Party Inventory","structureType":"area","children":[{"id":0,"identifier":"00000000-0000-0000-0000-000000000000","name":"Company Profile","structureType":"area","children":null,"attributes":null,"url":null},{"id":0,"identifier":"00000000-0000-0000-0000-000000000000","name":"Business Relationship","structureType":"area","children":null,"attributes":null,"url":null}],"attributes":null,"url":null}
```

I see the JSON request looks correct, but the response does not include any child nodes (see below) nor does the VSTS web app display any children for the new area node. It's interesting that the [REST API docs don't show the ability to add children](https://www.visualstudio.com/en-us/docs/integrate/api/wit/classification-nodes#create-an-area).

Response:

```json
{"id":1,"identifier":"<guid>","name":"Third Party Inventory","structureType":"area","hasChildren":false,"_links":{"self":{"href":"https://MYACCOUNT.visualstudio.com/{guid}/_apis/wit/classificationNodes/Areas/Third%20Party%20Inventory"},"parent":{"href":"https://MYACCOUNT.visualstudio.com/{guid}/_apis/wit/classificationNodes/Areas"}},"url":"https://MYACCOUNT.visualstudio.com/{guid}/_apis/wit/classificationNodes/Areas/Third%20Party%20Inventory"}​
```

What is the correct way to create sub-areas via the API?

**Comment by danhellem** [comment]
Hello Smithrobs,

I am going to assume you figured this out by now. Sorry for the delay in responses. I am going through and cleaning things up and looking at outstanding issues.

https://docs.microsoft.com/en-us/rest/api/vsts/wit/classification%20nodes/create%20or%20update?view=vsts#create_an_area

You need to create a node and then use that path to create the child nodes. If you are still having issues let me know and I can post some more sample code to help you.

Again, sorry for such a long delay in response.
