### ISSUE TITLE
ProfileHttpClient returns wrong account if signed into both Microsoft Account and Office 365

### ISSUE THREAD

**Issue by paulirwin** [Microsoft/vsts-dotnet-samples#64]
I couldn't find any other places to file this so if this is not in the right place, let me know and I'll file it elsewhere. This is what appears to be either a bug in the .NET client (version 15.112.1) or in VSTS OAuth itself.

Steps to reproduce:
1. In your browser, be signed in to both a Microsoft account that has access to one or more VSTS accounts, and also be signed in with a work Office 365 account (perhaps this would happen with Azure AD as well?) that does _not_ have access to any VSTS accounts. In my case, these are two different email addresses.
2. Initiate the OAuth redirect. On the approval page, asking if you approve giving access to the scopes for this application, notice that it shows your Microsoft account email. Click to approve the request.
3. After being redirected, the code below executes.
4. The `profile` variable contains your Office 365 account information, not your Microsoft account, and any subsequent calls fail (i.e. `AccountHttpClient.GetAccountsByMemberAsync` returns no results) because your Office 365 account does not have access to any VSTS accounts.

Code:
```C#
var vsoBaseUri = new Uri("https://app.vssps.visualstudio.com/");
var credential = new VssOAuthAccessTokenCredential(accessToken);

var profileClient = new ProfileHttpClient(vsoBaseUri, credential);
var profile = await profileClient.GetProfileAsync(new ProfileQueryContext(AttributesScope.Core));
```

The code above works correctly if you are only signed in with your Microsoft account (and signed out of your Office 365 account).

**Comment by justmarks** [comment]
@paulirwin can you reach out to me.  I don't think there's a bug here as I can't repro your issue.  Happy to debug with you

**Comment by paulirwin** [comment]
At first pass I can't reproduce it now either. It looks like something might have changed on the VSTS OAuth side. I'll reopen it if it comes up again.
