### ISSUE TITLE
Request sample clone with VssConnection

### ISSUE THREAD

**Issue by Dennis-Smurf** [Microsoft/vsts-dotnet-samples#72]
Can you give me an example how to clone a repository with VssClientCredentials? 
I'v already found how to download a zip file of a repository, but cannot find the clone option.

**Comment by vtbassmatt** [comment]
Thanks for opening an issue.

Clone is a Git protocol operation that doesn't map nicely to REST, and we don't have a REST controller for it. Clone (and other Git operations) are better suited to something like [libgit2](https://libgit2.github.com/).
