### ISSUE TITLE
[Example request] how to create task for VSTS

### ISSUE THREAD

**Issue by masters3d** [Microsoft/vsts-dotnet-samples#85]
I would like to use C# as much a possible to create a task in VSTS. 

Is this the correct avenue or is there something else in the works?

**Comment by danhellem** [comment]
You can use the create bug as an example. You just need to change the type to be task and make sure you have the correct task fields saved.

https://github.com/Microsoft/vsts-dotnet-samples/blob/master/ClientLibrary/Quickstarts/dotnet/WitQuickStarts/Samples/CreateBug.cs#L42

**Comment by masters3d** [comment]
Thanks! I ended up using a process execution which works great with command line apps. I just packaged up my exe inside the plug in.
```
....
  "execution": {
    "Process": {
      "target": "$(CurrentDirectory)\MyCSharpCommanline.exe $(inputField) $(inputField2) \"$(inputPath)\""
    }
  }

**Comment by masters3d** [comment]
task was ambiguous in this context, I meant build task extension.  This perhaps is not the best repo for this issue anyway.
