### ISSUE TITLE
VssConnection Security Rules violated by type

### ISSUE THREAD

**Issue by judavi** [Microsoft/vsts-dotnet-samples#88]
Hi, I'm trying to run the example from the readme but I'm getting this issue

![image](https://user-images.githubusercontent.com/1766933/33770191-a0a8557c-dc24-11e7-96af-7c45413d904d.png)

I'm using 'Microsoft.TeamFoundationServer.Client 15.122.1-preview', VS2017 and Windows 7 Enterprise

**Comment by judavi** [comment]
any thoughts @justmarks ?

**Comment by justmarks** [comment]
I haven't seen that error before.  I created a new .NETCore application with VS2017 (15.4.4) and after adding the NuGet package Microsoft.TeamFoundationServer.Client (15.122.1-preview) i got a different exception about Newtonsoft.JSON.  I then added that NuGet package (11.0.1-beta1) and the sample ran as expected.  Can you zip the solution+project and send it to us to see if we can repro, could be an environment issue we're unaware of

**Comment by cmaneu** [comment]
Hey there,
I got the exact same error on a .net 4.7.1 project.
I've tried to create a new .NETCore app and got the error from @justmarks.

Repro steps:
- Create a new .net console project (.Net FW)
- Add Microsoft.TeamFoundationServer.client and Microsoft.VisualStudio.Services.InteractiveClient latest preview packages
- Add the following code
- Execute

---c#
 VssBasicCredential credentials = new VssBasicCredential("", personalAccessToken);
            VssConnection connection = new VssConnection(new Uri(String.Format("https://{0}.visualstudio.com", vstsAccountName)), credentials);

            ProjectHttpClient projectHttpClient = connection.GetClient<ProjectHttpClient>();
            IEnumerable<TeamProjectReference> projects = projectHttpClient.GetProjects().Result;
---

**Comment by judavi** [comment]
Hi @justmarks thanks for your help. This is the project that I'm using as example https://github.com/judavi/deleteme/blob/master/TfsQueue.zip 
I removed my tokens, so is just replace for a correct one

**Comment by justmarks** [comment]
Thanks @judavi for the zip.  I ran it and saw the same error you did.  As a test, I copied the code into a new .NET Core app and it worked fine.  I then copied the code into a new .NET 4.6.1 project and after adding the NuGet package it worked perfectly.  I think there's something wrong with the references in your project.  Create a clean project and bring over what you need as you need it and you should be fine

**Comment by judavi** [comment]
Thanks @justmarks !
