### ISSUE TITLE
Add group to default team

### ISSUE THREAD

**Issue by lazyspark** [Microsoft/vsts-dotnet-samples#89]
Is it possible to add group to default team of a project? 

I see an API to create project but no API exists to associate project to a team. Or even add members to team. The team API doesn't seem to allow to add members to team.

**Comment by justmarks** [comment]
There is a new API coming this sprint allowing you to manage groups and users (Graph API).  Assuming you knew the group representing the team, you can simply add the AAD (or another VSTS) group to that team group.

Samples here: https://github.com/Microsoft/vsts-dotnet-samples/blob/master/ClientLibrary/Snippets/Microsoft.TeamServices.Samples.Client/Graph/GroupsSample.cs

**Comment by kbeckersbj** [comment]
How can you determine the team's group? I'm trying to add a user to a project's default team. I'm able to create the user into a new group, but I haven't figured out how to add a user into a team.
