### ISSUE TITLE
Get Merge Candidates

### ISSUE THREAD

**Issue by Zuul86** [Microsoft/vsts-dotnet-samples#91]
Is there any way to get a list of changesets when given a source and destination branch?  I thought there used to be a call GetMergeCandidates.

**Comment by vtbassmatt** [comment]
We don't have that in the REST API. Maybe it was in the SOAP client?

Feel free to file a bug reports for TFS/VSTS [here](http://developercommunity.visualstudio.com/) or a feature request [here](https://visualstudio.uservoice.com/forums/330519-team-services).
