### ISSUE TITLE
Need SDK sample for managing Capacity

### ISSUE THREAD

**Issue by InteXX** [Microsoft/vsts-dotnet-samples#94]
Is there any facility in the SDK for managing User Capacity in a given Iteration? If so, I'm not finding it.

An SDK sample would be very helpful here.

**Comment by danhellem** [comment]
No sorry InteXX. There is not way to just get the a users capacity for a given iteration. The best you can do is get the capacity per team for all the teams he is a member of and add it up.

https://docs.microsoft.com/en-us/rest/api/vsts/work/capacities?view=vsts

**Comment by InteXX** [comment]
I can probably do something with that...

Is there a corollary in the SDK?
